# Generated by Django 5.0.3 on 2024-08-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=200)),
                ('data_inicio', models.DateField(verbose_name='Data do evento')),
                ('data_final', models.DateField()),
                ('descricao', models.TextField()),
                ('tipo', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('local', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
            ],
        ),
    ]
