# Generated by Django 5.0.3 on 2024-08-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_eventos_gratuito_alter_eventos_data_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='quantidade_vagas',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
